///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Wealthings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ApplicationLogin recording.
    /// </summary>
    [TestModule("ebd38998-115c-4542-85f7-2350c67792ad", ModuleType.Recording, 1)]
    public partial class ApplicationLogin : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WealthingsRepository repository.
        /// </summary>
        public static WealthingsRepository repo = WealthingsRepository.Instance;

        static ApplicationLogin instance = new ApplicationLogin();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ApplicationLogin()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ApplicationLogin Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://test.wealthings.net' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://test.wealthings.net", "Chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(1));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(2));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WealthingsCom.Email' at 21;9.", repo.WealthingsCom.EmailInfo, new RecordItemIndex(3));
            //repo.WealthingsCom.Email.Click("21;9");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 20s.", new RecordItemIndex(4));
            Delay.Duration(20000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}dataart-for-test.use-only@wealthings.net{Tab}Alexander1+{Return}'.", new RecordItemIndex(5));
            Keyboard.Press("{Tab}dataart-for-test.use-only@wealthings.net{Tab}Alexander1+{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'WealthingsCom.Avatar'.", repo.WealthingsCom.AvatarInfo, new RecordItemIndex(6));
            Validate.Exists(repo.WealthingsCom.AvatarInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
