///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Wealthings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the WealthingsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    [RepositoryFolder("02e42b9a-da80-404d-968d-14ea963e1f66")]
    public partial class WealthingsRepository : RepoGenBaseFolder
    {
        static WealthingsRepository instance = new WealthingsRepository();
        WealthingsRepositoryFolders.WealthingsComAppFolder _wealthingscom;

        /// <summary>
        /// Gets the singleton class instance representing the WealthingsRepository element repository.
        /// </summary>
        [RepositoryFolder("02e42b9a-da80-404d-968d-14ea963e1f66")]
        public static WealthingsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public WealthingsRepository() 
            : base("WealthingsRepository", "/", null, 0, false, "02e42b9a-da80-404d-968d-14ea963e1f66", ".\\RepositoryImages\\WealthingsRepository02e42b9a.rximgres")
        {
            _wealthingscom = new WealthingsRepositoryFolders.WealthingsComAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("02e42b9a-da80-404d-968d-14ea963e1f66")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The WealthingsCom folder.
        /// </summary>
        [RepositoryFolder("08bfb280-30cd-418d-a92a-aca8157e766b")]
        public virtual WealthingsRepositoryFolders.WealthingsComAppFolder WealthingsCom
        {
            get { return _wealthingscom; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    public partial class WealthingsRepositoryFolders
    {
        /// <summary>
        /// The WealthingsComAppFolder folder.
        /// </summary>
        [RepositoryFolder("08bfb280-30cd-418d-a92a-aca8157e766b")]
        public partial class WealthingsComAppFolder : RepoGenBaseFolder
        {
            WealthingsRepositoryFolders.RootFolder _root;
            RepoItemInfo _emailInfo;
            RepoItemInfo _errormsgpopupInfo;
            RepoItemInfo _avatarInfo;

            /// <summary>
            /// Creates a new WealthingsCom  folder.
            /// </summary>
            public WealthingsComAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WealthingsCom", "/dom[@domain='test.wealthings.net']", parentFolder, 30000, null, false, "08bfb280-30cd-418d-a92a-aca8157e766b", "")
            {
                _root = new WealthingsRepositoryFolders.RootFolder(this);
                _emailInfo = new RepoItemInfo(this, "Email", ".//input[#'email']", 30000, null, "1091eb87-e93b-4300-9f8f-00e9dc8bbeab");
                _errormsgpopupInfo = new RepoItemInfo(this, "ErrorMsgPopup", "body/div[4]//p/?/?/span[@innertext~'^One\\ or\\ more\\ entries\\ you\\ h']", 30000, null, "efbd46f7-2257-4ff4-92de-6dc9cfd90d01");
                _avatarInfo = new RepoItemInfo(this, "Avatar", ".//div[#'root']//tag[@tagname='main']/div/div[1]/div[1]/div[2]/div[1]", 30000, null, "fe021f45-3328-4b37-a70e-949ae41c81c5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("08bfb280-30cd-418d-a92a-aca8157e766b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("08bfb280-30cd-418d-a92a-aca8157e766b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("1091eb87-e93b-4300-9f8f-00e9dc8bbeab")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("1091eb87-e93b-4300-9f8f-00e9dc8bbeab")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The ErrorMsgPopup item.
            /// </summary>
            [RepositoryItem("efbd46f7-2257-4ff4-92de-6dc9cfd90d01")]
            public virtual Ranorex.SpanTag ErrorMsgPopup
            {
                get
                {
                    return _errormsgpopupInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ErrorMsgPopup item info.
            /// </summary>
            [RepositoryItemInfo("efbd46f7-2257-4ff4-92de-6dc9cfd90d01")]
            public virtual RepoItemInfo ErrorMsgPopupInfo
            {
                get
                {
                    return _errormsgpopupInfo;
                }
            }

            /// <summary>
            /// The Avatar item.
            /// </summary>
            [RepositoryItem("fe021f45-3328-4b37-a70e-949ae41c81c5")]
            public virtual Ranorex.DivTag Avatar
            {
                get
                {
                    return _avatarInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Avatar item info.
            /// </summary>
            [RepositoryItemInfo("fe021f45-3328-4b37-a70e-949ae41c81c5")]
            public virtual RepoItemInfo AvatarInfo
            {
                get
                {
                    return _avatarInfo;
                }
            }

            /// <summary>
            /// The Root folder.
            /// </summary>
            [RepositoryFolder("cb97547f-81cd-4663-a666-6923c046c7ac")]
            public virtual WealthingsRepositoryFolders.RootFolder Root
            {
                get { return _root; }
            }
        }

        /// <summary>
        /// The RootFolder folder.
        /// </summary>
        [RepositoryFolder("cb97547f-81cd-4663-a666-6923c046c7ac")]
        public partial class RootFolder : RepoGenBaseFolder
        {
            RepoItemInfo _saveInfo;
            RepoItemInfo _addnewcontactInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _contactsInfo;
            RepoItemInfo _openmenuInfo;
            RepoItemInfo _logoutInfo;
            RepoItemInfo _signinInfo;
            RepoItemInfo _openerInfo;
            RepoItemInfo _iconcontactsInfo;
            RepoItemInfo _icheckhelperInfo;
            RepoItemInfo _icheckhelper1Info;

            /// <summary>
            /// Creates a new Root  folder.
            /// </summary>
            public RootFolder(RepoGenBaseFolder parentFolder) :
                    base("Root", ".//div[#'root']", parentFolder, 30000, null, false, "cb97547f-81cd-4663-a666-6923c046c7ac", "")
            {
                _saveInfo = new RepoItemInfo(this, "Save", ".//tag[@tagname='main']/div/div[1]/div[2]/ul/li[1]//span[@innertext='Save']", 30000, null, "3759c89a-61d7-4f35-b018-ae7145bdcccd");
                _addnewcontactInfo = new RepoItemInfo(this, "AddNewContact", ".//tag[@tagname='main']/div/div[3]/div[2]/div/button/span/span[@innertext='add new contact']", 30000, null, "49dfc8c7-59eb-4ec4-8d14-03c864061710");
                _lastnameInfo = new RepoItemInfo(this, "LastName", ".//tag[@tagname='main']/div/div[3]/div/div[2]/div/div[2]/div/div[1]/div/div[2]/div/input[@name='lastName']", 30000, null, "5037e40c-d95a-4a77-8548-cb094eb34af6");
                _firstnameInfo = new RepoItemInfo(this, "FirstName", ".//tag[@tagname='main']/div/div[3]/div/div[2]/div/div[2]/div/div[1]/div/div[3]/div/input[@name='firstName']", 30000, null, "e5d74daf-49cf-48d6-bad5-90ed362fca02");
                _contactsInfo = new RepoItemInfo(this, "Contacts", ".//?/?/?/nav/?/?//span[@innertext='Contacts']", 30000, null, "6b500b47-cd88-443c-92ee-70591406182c");
                _openmenuInfo = new RepoItemInfo(this, "OpenMenu", ".//header/div/a[@href~'^https://test\\.wealthings\\.n']", 30000, null, "ccee3937-df72-426b-a16c-5b2b39487348");
                _logoutInfo = new RepoItemInfo(this, "LogOut", ".//tag[@tagname='main']/div/div[1]/div[1]/div[2]/div[2]/div[1]/div[3]/a[@href~'^http://test\\.wealthings\\.ne']/span[@innertext='Log out']", 30000, null, "aa8c6111-4f33-4287-b779-9a7a10a63c11");
                _signinInfo = new RepoItemInfo(this, "SignIn", ".//form[@method='get']/strong/span[@innertext='Sign In']", 30000, null, "60418c0b-5d01-4ff7-bb8d-4eebd0f3c907");
                _openerInfo = new RepoItemInfo(this, "Opener", ".//nav/ul/li[5]/a/span[2]", 30000, null, "e4d8253d-8268-445a-b516-aaedfc8d57ce");
                _iconcontactsInfo = new RepoItemInfo(this, "IconContacts", ".//nav/ul/li[7]/?/?/i", 30000, null, "ce1776fc-c89e-4511-abd1-72c4e627215b");
                _icheckhelperInfo = new RepoItemInfo(this, "ICheckHelper", ".//tag[@tagname='main']/div/div[3]/div/div[2]/div/div[1]/div/div[2]/?/?/div/ins", 30000, null, "1ffa183f-226f-4771-83a4-781d204669db");
                _icheckhelper1Info = new RepoItemInfo(this, "ICheckHelper1", ".//tag[@tagname='main']/div/div[3]/div/div[2]/div/div[1]/div/div[1]/?/?/div/ins", 30000, null, "50407275-a913-4e7b-a209-e41ca22edfb2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cb97547f-81cd-4663-a666-6923c046c7ac")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cb97547f-81cd-4663-a666-6923c046c7ac")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Save item.
            /// </summary>
            [RepositoryItem("3759c89a-61d7-4f35-b018-ae7145bdcccd")]
            public virtual Ranorex.SpanTag Save
            {
                get
                {
                    return _saveInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Save item info.
            /// </summary>
            [RepositoryItemInfo("3759c89a-61d7-4f35-b018-ae7145bdcccd")]
            public virtual RepoItemInfo SaveInfo
            {
                get
                {
                    return _saveInfo;
                }
            }

            /// <summary>
            /// The AddNewContact item.
            /// </summary>
            [RepositoryItem("49dfc8c7-59eb-4ec4-8d14-03c864061710")]
            public virtual Ranorex.SpanTag AddNewContact
            {
                get
                {
                    return _addnewcontactInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AddNewContact item info.
            /// </summary>
            [RepositoryItemInfo("49dfc8c7-59eb-4ec4-8d14-03c864061710")]
            public virtual RepoItemInfo AddNewContactInfo
            {
                get
                {
                    return _addnewcontactInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("5037e40c-d95a-4a77-8548-cb094eb34af6")]
            public virtual Ranorex.InputTag LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("5037e40c-d95a-4a77-8548-cb094eb34af6")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("e5d74daf-49cf-48d6-bad5-90ed362fca02")]
            public virtual Ranorex.InputTag FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("e5d74daf-49cf-48d6-bad5-90ed362fca02")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The Contacts item.
            /// </summary>
            [RepositoryItem("6b500b47-cd88-443c-92ee-70591406182c")]
            public virtual Ranorex.SpanTag Contacts
            {
                get
                {
                    return _contactsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Contacts item info.
            /// </summary>
            [RepositoryItemInfo("6b500b47-cd88-443c-92ee-70591406182c")]
            public virtual RepoItemInfo ContactsInfo
            {
                get
                {
                    return _contactsInfo;
                }
            }

            /// <summary>
            /// The OpenMenu item.
            /// </summary>
            [RepositoryItem("ccee3937-df72-426b-a16c-5b2b39487348")]
            public virtual Ranorex.ATag OpenMenu
            {
                get
                {
                    return _openmenuInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The OpenMenu item info.
            /// </summary>
            [RepositoryItemInfo("ccee3937-df72-426b-a16c-5b2b39487348")]
            public virtual RepoItemInfo OpenMenuInfo
            {
                get
                {
                    return _openmenuInfo;
                }
            }

            /// <summary>
            /// The LogOut item.
            /// </summary>
            [RepositoryItem("aa8c6111-4f33-4287-b779-9a7a10a63c11")]
            public virtual Ranorex.SpanTag LogOut
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The LogOut item info.
            /// </summary>
            [RepositoryItemInfo("aa8c6111-4f33-4287-b779-9a7a10a63c11")]
            public virtual RepoItemInfo LogOutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The SignIn item.
            /// </summary>
            [RepositoryItem("60418c0b-5d01-4ff7-bb8d-4eebd0f3c907")]
            public virtual Ranorex.SpanTag SignIn
            {
                get
                {
                    return _signinInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SignIn item info.
            /// </summary>
            [RepositoryItemInfo("60418c0b-5d01-4ff7-bb8d-4eebd0f3c907")]
            public virtual RepoItemInfo SignInInfo
            {
                get
                {
                    return _signinInfo;
                }
            }

            /// <summary>
            /// The Opener item.
            /// </summary>
            [RepositoryItem("e4d8253d-8268-445a-b516-aaedfc8d57ce")]
            public virtual Ranorex.SpanTag Opener
            {
                get
                {
                    return _openerInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Opener item info.
            /// </summary>
            [RepositoryItemInfo("e4d8253d-8268-445a-b516-aaedfc8d57ce")]
            public virtual RepoItemInfo OpenerInfo
            {
                get
                {
                    return _openerInfo;
                }
            }

            /// <summary>
            /// The IconContacts item.
            /// </summary>
            [RepositoryItem("ce1776fc-c89e-4511-abd1-72c4e627215b")]
            public virtual Ranorex.ITag IconContacts
            {
                get
                {
                    return _iconcontactsInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The IconContacts item info.
            /// </summary>
            [RepositoryItemInfo("ce1776fc-c89e-4511-abd1-72c4e627215b")]
            public virtual RepoItemInfo IconContactsInfo
            {
                get
                {
                    return _iconcontactsInfo;
                }
            }

            /// <summary>
            /// The ICheckHelper item.
            /// </summary>
            [RepositoryItem("1ffa183f-226f-4771-83a4-781d204669db")]
            public virtual Ranorex.InsTag ICheckHelper
            {
                get
                {
                    return _icheckhelperInfo.CreateAdapter<Ranorex.InsTag>(true);
                }
            }

            /// <summary>
            /// The ICheckHelper item info.
            /// </summary>
            [RepositoryItemInfo("1ffa183f-226f-4771-83a4-781d204669db")]
            public virtual RepoItemInfo ICheckHelperInfo
            {
                get
                {
                    return _icheckhelperInfo;
                }
            }

            /// <summary>
            /// The ICheckHelper1 item.
            /// </summary>
            [RepositoryItem("50407275-a913-4e7b-a209-e41ca22edfb2")]
            public virtual Ranorex.InsTag ICheckHelper1
            {
                get
                {
                    return _icheckhelper1Info.CreateAdapter<Ranorex.InsTag>(true);
                }
            }

            /// <summary>
            /// The ICheckHelper1 item info.
            /// </summary>
            [RepositoryItemInfo("50407275-a913-4e7b-a209-e41ca22edfb2")]
            public virtual RepoItemInfo ICheckHelper1Info
            {
                get
                {
                    return _icheckhelper1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}