///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Wealthings.Contact
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreateContact recording.
    /// </summary>
    [TestModule("fcce9d5c-5976-4d6f-bb09-ac542a08871a", ModuleType.Recording, 1)]
    public partial class CreateContact : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Wealthings.WealthingsRepository repository.
        /// </summary>
        public static Wealthings.WealthingsRepository repo = Wealthings.WealthingsRepository.Instance;

        static CreateContact instance = new CreateContact();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateContact()
        {
            Input = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateContact Instance
        {
            get { return instance; }
        }

#region Variables

        string _Input;

        /// <summary>
        /// Gets or sets the value of variable Input.
        /// </summary>
        [TestVariable("0e7500fd-23dd-409a-9daf-f542ed72ea61")]
        public string Input
        {
            get { return _Input; }
            set { _Input = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WealthingsCom.Root.OpenMenu' at Center.", repo.WealthingsCom.Root.OpenMenuInfo, new RecordItemIndex(0));
            repo.WealthingsCom.Root.OpenMenu.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WealthingsCom.Root.Contacts' at 16;8.", repo.WealthingsCom.Root.ContactsInfo, new RecordItemIndex(1));
            repo.WealthingsCom.Root.Contacts.Click("16;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WealthingsCom.Root.AddNewContact' at 46;8.", repo.WealthingsCom.Root.AddNewContactInfo, new RecordItemIndex(2));
            repo.WealthingsCom.Root.AddNewContact.Click("46;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WealthingsCom.Root.LastName' at 52;9.", repo.WealthingsCom.Root.LastNameInfo, new RecordItemIndex(3));
            repo.WealthingsCom.Root.LastName.Click("52;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Input' with focus on 'WealthingsCom.Root.LastName'.", repo.WealthingsCom.Root.LastNameInfo, new RecordItemIndex(4));
            repo.WealthingsCom.Root.LastName.PressKeys(Input);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WealthingsCom.Root.FirstName' at 87;13.", repo.WealthingsCom.Root.FirstNameInfo, new RecordItemIndex(5));
            repo.WealthingsCom.Root.FirstName.Click("87;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Input' with focus on 'WealthingsCom.Root.FirstName'.", repo.WealthingsCom.Root.FirstNameInfo, new RecordItemIndex(6));
            repo.WealthingsCom.Root.FirstName.PressKeys(Input);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WealthingsCom.Root.Save' at 16;10.", repo.WealthingsCom.Root.SaveInfo, new RecordItemIndex(7));
            repo.WealthingsCom.Root.Save.Click("16;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating NotExists on item 'WealthingsCom.ErrorMsgPopup'.", repo.WealthingsCom.ErrorMsgPopupInfo, new RecordItemIndex(8));
            Validate.NotExists(repo.WealthingsCom.ErrorMsgPopupInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
