///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Wealthings.Contact
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Test recording.
    /// </summary>
    [TestModule("6426ee8e-93ab-4276-b287-5081f876a523", ModuleType.Recording, 1)]
    public partial class Test : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Wealthings.WealthingsRepository repository.
        /// </summary>
        public static Wealthings.WealthingsRepository repo = Wealthings.WealthingsRepository.Instance;

        static Test instance = new Test();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Test()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Test Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WealthingsCom.Root.IconContacts' at 16;10.", repo.WealthingsCom.Root.IconContactsInfo, new RecordItemIndex(0));
            repo.WealthingsCom.Root.IconContacts.Click("16;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WealthingsGoogleChrome.IntermediateD3DWindow' at 608;17.", repo.WealthingsGoogleChrome.IntermediateD3DWindowInfo, new RecordItemIndex(1));
            repo.WealthingsGoogleChrome.IntermediateD3DWindow.Click("608;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WealthingsCom.Root.AddNewContact' at 65;4.", repo.WealthingsCom.Root.AddNewContactInfo, new RecordItemIndex(2));
            repo.WealthingsCom.Root.AddNewContact.Click("65;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WealthingsCom.Root.LastName' at 205;18.", repo.WealthingsCom.Root.LastNameInfo, new RecordItemIndex(3));
            repo.WealthingsCom.Root.LastName.Click("205;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'supplier' with focus on 'WealthingsCom.Root.LastName'.", repo.WealthingsCom.Root.LastNameInfo, new RecordItemIndex(4));
            repo.WealthingsCom.Root.LastName.PressKeys("supplier");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WealthingsCom.Root.FirstName' at 156;10.", repo.WealthingsCom.Root.FirstNameInfo, new RecordItemIndex(5));
            repo.WealthingsCom.Root.FirstName.Click("156;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'supplierLname' with focus on 'WealthingsCom.Root.FirstName'.", repo.WealthingsCom.Root.FirstNameInfo, new RecordItemIndex(6));
            repo.WealthingsCom.Root.FirstName.PressKeys("supplierLname");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WealthingsCom.Root.ICheckHelper' at 5;8.", repo.WealthingsCom.Root.ICheckHelperInfo, new RecordItemIndex(7));
            repo.WealthingsCom.Root.ICheckHelper.Click("5;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WealthingsCom.Root.Save' at 9;8.", repo.WealthingsCom.Root.SaveInfo, new RecordItemIndex(8));
            repo.WealthingsCom.Root.Save.Click("9;8");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
